### ISSUE TITLE
Example renders in the README

### ISSUE THREAD

**Issue by mcous** [tracespace/pcb-stackup#14]
![arduino-top](https://cloud.githubusercontent.com/assets/2963448/16046141/5bfba2d2-3219-11e6-8131-92c769218d62.png) ![arduino-bottom](https://cloud.githubusercontent.com/assets/2963448/16046149/5fbb5b88-3219-11e6-8358-08f3b1bce9ac.png)

**Comment by mcous** [comment]
Put the top render into the README with 781b6da

**Comment by mcous** [comment]
[Some hackers are giving us crap](https://news.ycombinator.com/item?id=12157502) because the README image is a PNG file (hello Hacker News!).

Got a point, though, it's kinda stupid. Gonna push these example renders to gh-pages and reference them from there (image tag with SVG as src should work)

**Comment by kasbah** [comment]
Oh, that's where the traffic was coming from. Should we add this one? ![](https://img.shields.io/badge/badges-9-ff69b4.svg) 

The amazing thing about that one is that it's self inclusive!

**Comment by mcous** [comment]
You have no idea how much I like that
