### ISSUE TITLE
Gitter.im Chat?

### ISSUE THREAD

**Issue by kasbah** [tracespace/pcb-stackup#34]
Should we make a [gitter.im](https://gitter.im) chat for this repo so I can complain about the CI builds? :smiling_imp: 

In all seriousness, seems like it's got a bit of attention so people might need some help that can easier be handled in chat, and we can have quicker back and forth if we happen to be working at the same time.

**Comment by mcous** [comment]
Sure! I've never used gitter before, so do you have the necessary permissions to set it up?

**Comment by kasbah** [comment]
:tada: No, only you can do it right now because you need some organization level permissions it seems.
