### ISSUE TITLE
Rename layerType property to type

### ISSUE THREAD

**Issue by kasbah** [tracespace/pcb-stackup#41]
Was just looking at [index.js#L76](https://github.com/tracespace/pcb-stackup/blob/de20fb9280788d4379e220e6869076601e27fc70/index.js#L76). If we used the same name as core here it would just be:

```js
stackup.layers = stackupLayers
```
Since we now have a converter property in the cache users could pass it directly to core if they wanted to. 

Alternatively we could rename the property to `layerType` in core.

**Comment by mcous** [comment]
Yeah, I was thinking yesterday it was kinda weird how core and main didn't line up. I think `layer.type` is fine, unless you can think of any other kinds of `type`s we would want to add to a layer
