### ISSUE TITLE
Drills not rendered properly on FM_Transmitter board

### ISSUE THREAD

**Issue by kasbah** [tracespace/pcb-stackup#9]
Can't quite figure out why the drills aren't working properly with [this one](https://github.com/kasbah/pcb-stackup-test/tree/master/gerbers/FM_Transmitter).

Output: https://github.com/kasbah/pcb-stackup-test/blob/master/output/FM_Transmitter-top.svg

**Comment by mcous** [comment]
It looks like the drill file uses 2:5 precision (default for drill files in inches is 2:4) and keep trailing zero suppression (drill file default is to keep leading zeros). I added

```
;FILE_FORMAT=2:5
INCH,TZ
```

to get the file to render properly (using gerber-to-svg@1.0.0 last night)

**Comment by mcous** [comment]
Closing because it's a drill file issue and not a library issue
